language: android
jdk: oraclejdk8
sudo: required
android:
  components:
  - tools
  - platform-tools
  - android-26
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_script:
  - curl -s "https://cmake.org/files/v3.15/cmake-3.15.4-Linux-x86_64.tar.gz" | sudo tar --strip-components=1 -xz -C /usr/local
  - echo "cmake.dir=/usr/local" | tee -a local.properties
  - sudo chmod +x gradlew
  - git clone https://github.com/rafal1137/NDK_ETL.git
  - mv NDK_ETL $HOME
  - export ANDROID_NDK_HOME=$HOME/NDK_ETL/ndk-bundle
  - chmod -R 775 $HOME/NDK_ETL/ndk-bundle
before_install:
  - echo yes | sdkmanager "platform-tools" "platforms;android-26" "build-tools;25.0.2" "tools" "system-images;android-S;google_apis_playstore;arm64-v8a"
  # Emulator Management: Create, Start and Wait
  - echo no | avdmanager create avd --force -n test -k system-images;android-S;google_apis_playstore;arm64-v8a --abi google_apis/arm64-v8a
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - ./gradlew assembleDebug
after_script:
  # now run the tests
  - ./gradlew connectedAndroidTest
