language: c

compiler:
  - gcc

env:
  native:
    - BUNDLED_LIBS=0
    - CROSS_COMPILE32=0

before_install:
  - sudo apt-get update
  - sudo apt-get install libsdl1.2-dev:i386 libvorbis-dev:i386 libjpeg8-dev:i386 libcurl4-openssl-dev:i386

script:
  - ./easybuild.sh

notifications:
  irc:
    channels:
      - "irc.freenode.org#etlegacy"
    use_notice: true
    skip_join: true
