language: cpp

compiler:
  - gcc
  - clang

env:
  native:
    - BUNDLED_LIBS=1
    - CROSS_COMPILE32=0
    - FEATURE_RENDERER2=1
    - RENDERER_DYNAMIC=1

script:
  - ./easybuild.sh

notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.org#etlegacy"
    use_notice: true
    skip_join: true
