language: c

compiler:
  - gcc
  - clang

env:
  native:
    - BUNDLED_LIBS=0
    - CROSS_COMPILE32=0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsdl1.2-dev libvorbis-dev libjpeg8-dev libcurl4-openssl-dev liblua5.1-dev libglew-dev

script:
  - ./easybuild.sh

notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.org#etlegacy"
    use_notice: true
    skip_join: true
