# default in trusty is GCC 4.8, Clang 3.5, cmake 3.2
# https://github.com/travis-ci/apt-source-whitelist

language: cpp
dist: trusty
sudo: false

env:
  global:
    - CROSS_COMPILE32=0
    - BUNDLED_LIBS=1
    - BUNDLED_SDL=1
    - BUNDLED_ZLIB=1
    - BUNDLED_MINIZIP=1
    - BUNDLED_JPEG=1
    - BUNDLED_LUA=1
    - BUNDLED_OGG=1
    - INSTALL_EXTRA=0

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        sources:
        - ubuntu-toolchain-r-test
        apt:
          packages:
          - nasm
          - libasound2-dev
          - pulseaudio
    - os: linux
      compiler: clang
      addons:
        sources:
        - llvm-toolchain-trusty
        apt:
          packages:
          - nasm
          - libasound2-dev
          - pulseaudio
    #- os: osx
    #  osx_image: xcode8.3
    #  before_install:
    #    - brew update
    #    - brew install gnu-sed nasm
    #    - brew outdated automake || brew upgrade automake
    #    - brew outdated autoconf || brew upgrade autoconf
    #  env:
    #    - CXX=clang++ CC=clang
    #    - CXXFLAGS="-g -lstdc++"

before_script:
  # workaround for missing automake 1.15
  - cd libs/jpegturbo
  - autoreconf -fvi
  - cd ../..

script:
  - ./easybuild.sh

notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.org#etlegacy"
    use_notice: true
    skip_join: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5a93d4b59447e6129a58
    on_success: change
    on_failure: always
    on_start: never
