#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 2.75.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
	# whitelist
	only:
		- master

# Build worker image (VM template)
image: Visual Studio 2015

# environment variables
environment:
	VisualStudioVersion: 14.0

# scripts that run after cloning repository
install:
	- cmd: git submodule update --init --recursive

# to run your custom scripts instead of automatic MSBuild
build_script:
	- "easybuild.bat clean build package"

# to disable automatic builds
build: off

# to disable automatic tests
test: off

# Disable deploy
deploy: off

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
	# Gitter Webhook
	- provider: Webhook
		url: https://webhooks.gitter.im/e/88b2318a9e31215be0c9
		on_build_success: false
		on_build_failure: true
		on_build_status_changed: true
